/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiringpi_jni_WiringPiI2C */

#ifndef _Included_com_wiringpi_jni_WiringPiI2C
#define _Included_com_wiringpi_jni_WiringPiI2C
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiringpi_jni_WiringPiI2C
 * Method:    wiringPiI2CRead
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wiringpi_jni_WiringPiI2C_wiringPiI2CRead
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_wiringpi_jni_WiringPiI2C
 * Method:    wiringPiI2CReadReg8
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wiringpi_jni_WiringPiI2C_wiringPiI2CReadReg8
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_wiringpi_jni_WiringPiI2C
 * Method:    wiringPiI2CReadReg16
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wiringpi_jni_WiringPiI2C_wiringPiI2CReadReg16
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_wiringpi_jni_WiringPiI2C
 * Method:    wiringPiI2CWrite
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_wiringpi_jni_WiringPiI2C_wiringPiI2CWrite
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_wiringpi_jni_WiringPiI2C
 * Method:    wiringPiI2CWriteReg8
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_wiringpi_jni_WiringPiI2C_wiringPiI2CWriteReg8
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_wiringpi_jni_WiringPiI2C
 * Method:    wiringPiI2CWriteReg16
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_wiringpi_jni_WiringPiI2C_wiringPiI2CWriteReg16
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_wiringpi_jni_WiringPiI2C
 * Method:    wiringPiI2CSetupInterface
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_wiringpi_jni_WiringPiI2C_wiringPiI2CSetupInterface
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_wiringpi_jni_WiringPiI2C
 * Method:    wiringPiI2CSetup
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wiringpi_jni_WiringPiI2C_wiringPiI2CSetup
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
