/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_wiringpi_jni_SoftTone.h"
#include <softTone.h>

/*
 * Class:     com_wiringpi_jni_SoftTone
 * Method:    softToneCreate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wiringpi_jni_SoftTone_softToneCreate(JNIEnv *env, jclass clazz, jint pin) {
    return softToneCreate(pin);
}

/*
 * Class:     com_wiringpi_jni_SoftTone
 * Method:    softToneStop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiringpi_jni_SoftTone_softToneStop(JNIEnv *env, jclass clazz, jint pin) {
    softToneStop(pin);
}

/*
 * Class:     com_wiringpi_jni_SoftTone
 * Method:    softToneWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiringpi_jni_SoftTone_softToneWrite(JNIEnv *env, jclass clazz, jint pin, jint freq) {
    softToneWrite(pin, freq);
}
