/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiringpi_jni_SoftTone */

#ifndef _Included_com_wiringpi_jni_SoftTone
#define _Included_com_wiringpi_jni_SoftTone
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiringpi_jni_SoftTone
 * Method:    softToneCreate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_wiringpi_jni_SoftTone_softToneCreate
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_wiringpi_jni_SoftTone
 * Method:    softToneStop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiringpi_jni_SoftTone_softToneStop
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_wiringpi_jni_SoftTone
 * Method:    softToneWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiringpi_jni_SoftTone_softToneWrite
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
