/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wiringpi_jni_TestNative */

#ifndef _Included_com_wiringpi_jni_TestNative
#define _Included_com_wiringpi_jni_TestNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wiringpi_jni_TestNative
 * Method:    fun
 * Signature: (ILjava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_com_wiringpi_jni_TestNative_fun
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_wiringpi_jni_TestNative
 * Method:    wiringPiISR
 * Signature: (IILjava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_com_wiringpi_jni_TestNative_wiringPiISR
  (JNIEnv *, jclass, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
