/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_wiringpi_jni_SoftPwm.h"
#include <softPwm.h>

/*
 * Class:     com_wiringpi_jni_SoftPwm
 * Method:    softPwmCreate
 * Signature: (III)I
 */
JNIEXPORT jint
JNICALL Java_com_wiringpi_jni_SoftPwm_softPwmCreate(JNIEnv *env, jclass clazz, jint pin, jint value, jint range) {
    return softPwmCreate(pin, value, range);
}

/*
 * Class:     com_wiringpi_jni_SoftPwm
 * Method:    softPwmWrite
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_wiringpi_jni_SoftPwm_softPwmWrite(JNIEnv *env, jclass clazz, jint pin, jint value) {
    softPwmWrite(pin, value);
}

/*
 * Class:     com_wiringpi_jni_SoftPwm
 * Method:    softPwmStop
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_wiringpi_jni_SoftPwm_softPwmStop(JNIEnv *env, jclass clazz, jint pin) {
    softPwmStop(pin);
}

