/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_wiringpi_jni_TestNative.h"
#include "Callback.h"
#include <wiringPi.h>
#include <softTone.h>
#include  <wiringPiI2C.h>

/*
 * Class:     com_wiringpi_jni_TestNative
 * Method:    fun
 * Signature: (ILjava/lang/Runnable;)V
 */
JNIEXPORT void JNICALL Java_com_wiringpi_jni_TestNative_fun(JNIEnv *env, jclass clazz, jint num, jobject runnable) {
    jclass cls = (*env).GetObjectClass(runnable);
    jmethodID methodRunId = (*env).GetMethodID(cls, "run", "()V");
    (*env).CallVoidMethod(runnable, methodRunId);
    funcs[num]();
}


JNIEXPORT void
JNICALL Java_com_wiringpi_jni_TestNative_wiringPiISR(JNIEnv *env, jclass clazz, jint pin, jint mode, jobject runnable) {
    wiringPiISR(pin, mode, funcs[pin]);
}
